CREATE TABLE Faculties
(
  FacultyID INT NOT NULL AUTO_INCREMENT,
  Faculty VARCHAR(32) NOT NULL,
  Fee INT NOT NULL,
  Level INT NOT NULL,
  PRIMARY KEY (FacultyID)
);

CREATE TABLE Companies
(
  CompanyID INT NOT NULL AUTO_INCREMENT,
  Company VARCHAR(32) NOT NULL,
  Image VARCHAR(32) NOT NULL,
  Value INT NOT NULL,
  WorkTime INT NOT NULL,
  PRIMARY KEY (CompanyID)
);

CREATE TABLE Students
(
  StudentID INT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(32) NOT NULL UNIQUE,
  Email VARCHAR(32) NOT NULL UNIQUE,
  Age INT NOT NULL,
  Life INT NOT NULL,
  Emotion INT NOT NULL,
  Money INT NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Level INT NOT NULL,
  FacultyID INT,
  CompanyID INT,
  PRIMARY KEY (StudentID),
  FOREIGN KEY (FacultyID) REFERENCES Faculties(FacultyID),
  FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID)
);

CREATE TABLE Houses
(
  IdHouses INT NOT NULL AUTO_INCREMENT,
  Image VARCHAR(32) NOT NULL,
  Price INT NOT NULL,
  Tipology VARCHAR(3) NOT NULL,
  StudentID INT NOT NULL,
  PRIMARY KEY (IdHouses),
  FOREIGN KEY (StudentID) REFERENCES Students(StudentID)
);